# Generated by Django 6.0.2 on 2026-03-17 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("reg_number", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(max_length=200)),
                ("level", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("phone", models.CharField(max_length=20)),
                ("blood_group", models.CharField(max_length=5)),
                ("genotype", models.CharField(max_length=5)),
                ("address", models.TextField()),
                ("emergency_contact", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
