# Generated by Django 6.0.2 on 2026-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="medical_id",
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="emergency_contact",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="reg_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
