# Generated by Django 6.0.2 on 2026-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_appointment_admin_note_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="admin_note",
            new_name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="cancelled_by_admin",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular Check-up"),
                    ("Emergency", "Emergency"),
                    ("Freshers", "Freshers Medical"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
