# Generated by Django 6.0.2 on 2026-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_rename_admin_note_appointment_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="card",
            field=models.FileField(blank=True, null=True, upload_to="student_cards/"),
        ),
    ]
