# Generated by Django 6.0.2 on 2026-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0007_student_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="clinic_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="treated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
