# Generated by Django 6.0.2 on 2026-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0008_appointment_clinic_notes_appointment_diagnosis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="doctor_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="password",
            field=models.CharField(default="doctor123", max_length=100),
        ),
    ]
