# Generated by Django 6.0.2 on 2026-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0010_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
