# Generated by Django 6.0.2 on 2026-05-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0011_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="doctors/"),
        ),
    ]
