# Generated by Django 6.0.2 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0012_doctor_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
